export const eastAfricanCountries = [
  {
    code: "+254",
    country: "Kenya",
    counties: [
      "Baringo",
      "Bomet",
      "Bungoma",
      "Busia",
      "Elgeyo-Marakwet",
      "Embu",
      "Garissa",
      "Homa Bay",
      "Isiolo",
      "Kajiado",
      "Kakamega",
      "Kericho",
      "Kiambu",
      "Kilifi",
      "Kirinyaga",
      "Kisii",
      "Kisumu",
      "Kitui",
      "Kwale",
      "Laikipia",
      "Lamu",
      "Machakos",
      "Makueni",
      "Mandera",
      "Marsabit",
      "Meru",
      "Migori",
      "Mombasa",
      "Murang'a",
      "Nairobi",
      "Nakuru",
      "Nandi",
      "Narok",
      "Nyamira",
      "Nyandarua",
      "Nyeri",
      "Samburu",
      "Siaya",
      "Taita Taveta",
      "Tana River",
      "Tharaka-Nithi",
      "Trans Nzoia",
      "Turkana",
      "Uasin Gishu",
      "Vihiga",
      "Wajir",
      "West Pokot",
    ],
  },

  {
    code: "+255",
    country: "Tanzania",
    counties: [
      "Arusha",
      "Dar es Salaam",
      "Dodoma",
      "Geita",
      "Iringa",
      "Kagera",
      "Kigoma",
      "Kilimanjaro",
      "Mara",
      "Mbeya",
      "Morogoro",
      "Mtwara",
      "Mwanza",
      "Pwani",
      "Shinyanga",
      "Singida",
      "Tabora",
      "Tanga",
      "Zanzibar",
    ],
  },

  {
    code: "+256",
    country: "Uganda",
    counties: [
      "Arua",
      "Gulu",
      "Jinja",
      "Kabale",
      "Kampala",
      "Kasese",
      "Lira",
      "Masaka",
      "Mbale",
      "Mbarara",
      "Mukono",
      "Wakiso",
    ],
  },

  {
    code: "+250",
    country: "Rwanda",
    counties: [
      "Bugesera",
      "Burera",
      "Gakenke",
      "Gasabo",
      "Huye",
      "Kayonza",
      "Kicukiro",
      "Musanze",
      "Ngoma",
      "Nyagatare",
      "Rubavu",
      "Rusizi",
    ],
  },
];
